language: clojure

lein: lein

dist: trusty

sudo: required

jdk:
   - oraclejdk8

services:
  - docker

addons:
  apt:
    packages:
      - gnuplot
      - gnuplot-x11

before_install:
  - cd ${TRAVIS_BUILD_DIR}/jepsen

before_script:
  - docker-compose up -d

script:
  - lein cljfmt check
  - lein clean
  - lein test
